# Generated by Django 5.1.7 on 2025-03-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipos', models.CharField(max_length=100, verbose_name='Tipos')),
                ('peso', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Altura')),
            ],
        ),
    ]
